#:schema node_modules/wrangler/config-schema.json
name = "ayutayaweb"
compatibility_date = "2025-03-11"
main = "./svc/server.ts"
assets = { directory = "./dist" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ayutayaweb"
database_id = "aca89336-ab7c-4a8d-a6f4-22d258fd86dd"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "ayutayaweb2"
database_id = "e52ae02f-f026-4bdb-a6d3-54bbda426a19"
